# Generated by Django 4.2 on 2024-01-15 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('churches', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_id', models.CharField(max_length=20, unique=True)),
                ('family_name', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'members_family',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=20, unique=True)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('separated', 'Separated')], max_length=20)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('education_level', models.CharField(blank=True, max_length=50)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('salvation_date', models.DateField(blank=True, null=True)),
                ('baptism_date', models.DateField(blank=True, null=True)),
                ('membership_date', models.DateField(default=django.utils.timezone.now)),
                ('spiritual_gifts', models.JSONField(blank=True, default=list)),
                ('family_role', models.CharField(blank=True, max_length=50)),
                ('welfare_category', models.CharField(choices=[('none', 'No Special Needs'), ('pwd', 'Person with Disability'), ('widow', 'Widow/Widower'), ('senior', 'Senior Citizen'), ('orphan', 'Orphan'), ('medical', 'Medical Needs'), ('financial', 'Financial Assistance'), ('housing', 'Housing Needs'), ('employment', 'Employment Support')], default='none', max_length=50)),
                ('special_needs', models.JSONField(blank=True, default=list)),
                ('welfare_notes', models.TextField(blank=True)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('deceased', 'Deceased')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='churches.branch')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='members.family')),
                ('relationship_manager', models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Relationship Managers', 'Branch Managers']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_member',
                'ordering': ['member_id'],
                'indexes': [models.Index(fields=['member_id'], name='members_mem_member_i_123456_idx'), models.Index(fields=['branch', 'membership_status'], name='members_mem_branch_i_789012_idx'), models.Index(fields=['welfare_category'], name='members_mem_welfare_345678_idx')],
            },
        ),
        migrations.CreateModel(
            name='WelfareCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(choices=[('financial', 'Financial Assistance'), ('medical', 'Medical Support'), ('housing', 'Housing Needs'), ('employment', 'Employment Support'), ('counseling', 'Counseling'), ('prayer', 'Prayer Support'), ('education', 'Educational Support'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('target_resolution_date', models.DateField(blank=True, null=True)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_officer', models.ForeignKey(blank=True, limit_choices_to={'groups__name__in': ['Welfare Officers', 'Relationship Managers']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_welfare_cases', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='welfare_cases', to='members.member')),
            ],
            options={
                'db_table': 'members_welfare_case',
                'ordering': ['-reported_date'],
                'indexes': [models.Index(fields=['member', 'status'], name='members_wel_member_i_123456_idx'), models.Index(fields=['case_type', 'urgency'], name='members_wel_case_ty_789012_idx'), models.Index(fields=['assigned_officer', 'status'], name='members_wel_assigne_345678_idx')],
            },
        ),
        migrations.CreateModel(
            name='WelfareUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_notes', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('next_steps', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('welfare_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='members.welfarecase')),
            ],
            options={
                'db_table': 'members_welfare_update',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MinistryParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('leader', 'Leader'), ('coordinator', 'Coordinator'), ('head', 'Department Head')], default='member', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ministry_participation', to='members.member')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.ministry')),
            ],
            options={
                'db_table': 'members_ministry_participation',
                'unique_together': {('member', 'ministry')},
                'indexes': [models.Index(fields=['member', 'is_active'], name='members_min_member_i_123456_idx'), models.Index(fields=['ministry', 'role'], name='members_min_ministry_789012_idx')],
            },
        ),
        migrations.CreateModel(
            name='MemberEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_streak', models.IntegerField(default=0)),
                ('monthly_attendance_rate', models.FloatField(default=0.0)),
                ('last_attendance_date', models.DateField(blank=True, null=True)),
                ('ministry_involvement', models.JSONField(blank=True, default=dict)),
                ('event_participation', models.JSONField(blank=True, default=dict)),
                ('last_communication', models.DateTimeField(blank=True, null=True)),
                ('communication_response_rate', models.FloatField(default=0.0)),
                ('giving_consistency', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(default=0.0)),
                ('engagement_tier', models.CharField(choices=[('high', 'High Engagement'), ('medium', 'Medium Engagement'), ('low', 'Low Engagement'), ('inactive', 'Inactive')], default='medium', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='members.member')),
            ],
            options={
                'db_table': 'members_member_engagement',
            },
        ),
        migrations.AddField(
            model_name='family',
            name='primary_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_family', to='members.member'),
        ),
    ]
